name: pippi
on: [pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'stb'
        dry-run: true
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'stb'
        fuzz-seconds: 900
        dry-run: true
    - name: Upload Crash
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: artifacts
        path: ./out/artifacts
